routes/web.php
<?php

use App\Http\Controllers\CurrencyController;
use App\Http\Controllers\PortfolioController;
use Illuminate\Support\Facades\Route;
use Swoole\Server\Port;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource("currencies", CurrencyController::class)->only(["index","store"]);
Route::resource("portfolio", PortfolioController::class)->except(["show"]);
Route::get("portfolio/{portfolio}/delete", [PortfolioController::class,"delete"])->name("portfolio.delete");
Route::get("portfolio/refresh", [PortfolioController::class, "refresh_rates"])->name("portfolio.refresh");

app/Models/Currency.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Currency extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $casts = [
        "rate_date" => "date"
    ];

    public static function search(string $search)
    {
        if (empty($search)) {
            return static::query();
        }

        return static::query()->where("name", "LIKE", "%{$search}%")
            ->orWhere("code", "LIKE", "%{$search}%");
    }

    public function portfolios(): HasMany
    {
        return $this->hasMany(Portfolio::class, "currency_id");
    }
}

app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use App\Handlers\CurrencyUpdater;
use App\Models\Currency;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class CurrencyController extends Controller
{
    public function index()
    {
        $latest_date = Currency::first()->rate_date;

        $currencies =  Currency::with(["portfolios"])->get();

        return view("currencies.index", [
            "currencies" => $currencies,
            "latest_date" => $latest_date
        ]);
    }

    public function store()
    {
        CurrencyUpdater::update();
        alert()->success("success", "Currency rates updated");

        return redirect()->route("currencies.index");
    }
}

app/Http/Livewire/CurrencyForm.php
<?php

namespace App\Http\Livewire;

use App\Models\Currency;
use App\Models\Portfolio;
use Livewire\Component;

class CurrencyForm extends Component
{
    public $currency;
    public $search;

    public function mount(Portfolio $portfolio = null, Currency $currency = null)
    {
        $this->search = "";
        $this->currency = null;

        if (isset($portfolio->id)) {
            $currency = $portfolio->currency;
            $this->currency = $currency->id;
        }

        if (isset($currency->id)) {
            $this->currency = $currency->id;
        }
    }

    public function render()
    {
        return view('livewire.currency-form', [
            "currencies" => Currency::search($this->search)->get()
        ]);
    }
}

resources/views/currencies/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="flex flex-col gap-4">
        <header class="flex flex-row gap-4 items-center justify-between">
            <section class="flex-col gap-4">
                <h2>Currency List</h2>
                <h3>Latest Date Updated: {{ $latest_date->format('Y-m-d') }}</h3>
            </section>
            <form action="{{ route('currencies.store') }}" method="POST">
                @csrf

                <button class="btn btn-outline-secondary flex gap-2 items-center" type="submit">
                    <x-lineawesome-redo-alt-solid class="w-6 h-6" />
                    <span>Refresh Rates</span>
                </button>

            </form>
        </header>

        @livewire('currency-list')
    </section>
@endsection