routes/web.php
<?php

use App\Http\Controllers\CurrencyController;
use App\Http\Controllers\PortfolioController;
use Illuminate\Support\Facades\Route;
use Swoole\Server\Port;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource("currencies", CurrencyController::class)->only(["index","store"]);
Route::resource("portfolio", PortfolioController::class)->except(["show"]);
Route::get("portfolio/{portfolio}/delete", [PortfolioController::class,"delete"])->name("portfolio.delete");
Route::get("portfolio/refresh", [PortfolioController::class, "refresh_rates"])->name("portfolio.refresh");

app/Models/Portfolio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Portfolio extends Model
{
    use HasUuids;
    use HasFactory;

    protected $guarded = [];

    public static function search(string $search)
    {
        if (empty($search)) {
            return static::query();
        }

        return static::query()->whereHas("currency", function (Builder  $query) use ($search) {
            $query->where("name", "LIKE", "%{$search}%")
            ->orWhere("code", "LIKE", "%{$search}%");
        });
    }

    public function currency(): BelongsTo
    {
        return $this->belongsTo(Currency::class, "currency_id");
    }
}

app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;

use App\Handlers\CurrencyUpdater;
use App\Models\Portfolio;
use Illuminate\Http\Request;

class PortfolioController extends Controller
{
    public function index()
    {
        return view(
            "portfolio.index",
            [
                "portfolios" => Portfolio::with("currency")->get()
            ]
        );
    }

    public function create()
    {
        $currency = request()->query("currency");

        if (isset($currency)) {
            return view("portfolio.create", [
                "currency" => $currency
            ]);
        }

        return view("portfolio.create");
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            "currency_id" => "required|integer|exists:currencies,id|unique:portfolios,currency_id",
        ]);

        $portfolio = Portfolio::create($validated);
        alert()->success("success", "Currency added successfully to Portfolio");

        return redirect()->route("portfolio.index");
    }

    public function edit(Portfolio $portfolio)
    {
        return view("portfolio.edit", [
            "portfolio" => $portfolio->load("currency")
        ]);
    }

    public function update(Request $request, Portfolio $portfolio)
    {
        $validated = $request->validate([
            "currency_id" => "required|integer|exists:currencies,id|unique:portfolios,currency_id,".$portfolio->id,
        ]);

        $portfolio->update($validated);

        alert()->success("success", "Portfolio updated successfully");

        return redirect()->route('portfolio.index');
    }

    public function delete(Portfolio $portfolio)
    {
        return view("portfolio.delete", [
            "portfolio" => $portfolio->load("currency")
        ]);
    }

    public function destroy(Portfolio $portfolio)
    {
        $portfolio->delete();

        alert()->success("success", "Currency deleted successfully from Portfolio");

        return redirect()->route("portfolio.index");
    }

    public function refresh_rates()
    {
        CurrencyUpdater::update();

        alert()->success("success", "Rates successfully refreshed");

        return redirect()->route("portfolio.index");
    }
}

resources/views/portfolio/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="flex flex-col gap-4">
        <header>
            <h2>Add New Currency</h2>
        </header>

        <form action="{{ route('portfolio.store') }}" method="POST">
            @csrf

            @if (isset($currency))
                @livewire('currency-form', ['currency' => $currency])
            @else
                @livewire('currency-form')
            @endif
        </form>
    </section>
@endsection

resources/views/portfolio/delete.blade.php
@extends('layouts.app')

@section('content')
    <section class="flex flex-col gap-4">
        <header>
            <h2>Delete {{ $portfolio->currency->name }} {{ $portfolio->currency->code }}?</h2>
        </header>

        <section class="section flex flex-col gap-4">
            <p>Are you sure you want to delete? This is irreversible</p>
            <form action="{{ route('portfolio.destroy', ['portfolio' => $portfolio]) }}" method="POST"
                class="flex gap-2 items-center">
                @csrf
                @method('DELETE')
                <button type="submit" class="flex gap-2 items-center btn btn-primary">
                    <x-lineawesome-thumbs-up-solid class="w-6 h-6" />
                    <span>Yes please!</span>
                </button>
                <a class="btn btn-outline-error" href="{{ route('portfolio.index') }}">
                    <x-lineawesome-thumbs-down-solid class="w-6 h-6" />
                    <span>No, thanks</span>
                </a>
            </form>
        </section>
    </section>
@endsection

resources/views/portfolio/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="flex flex-col gap-4">
        <header>
            <h2>Edit Portfolio Currency</h2>
        </header>
        <form action="{{ route('portfolio.update', ['portfolio' => $portfolio]) }}" method="POST">
            @csrf
            @method('PATCH')
            @livewire('currency-form', ['portfolio' => $portfolio])
        </form>
    </section>
@endsection

resources/views/portfolio/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="flex flex-col gap-4">
        <header class="flex gap-4 justify-between">
            <h2>My Portfolio</h2>
            <section class="flex items-center gap-2">
                <a class="btn btn-secondary flex gap-2 items-center" href="{{ route('portfolio.create') }}">
                    <x-lineawesome-plus-circle-solid class="w-6 h-6" />
                    <span>Add New Currency</span>
                </a>
                <a class="btn btn-outline-secondary flex gap-2 items-center" href="{{ route('portfolio.refresh') }}">
                    <x-lineawesome-redo-alt-solid class="w-6 h-6" />
                    <span>Refresh Rates</span>
                </a>
            </section>
        </header>

        @livewire('portfolio-list')

    </section>
@endsection