routes/web.php
<?php

use App\Http\Controllers\CurrencyController;
use App\Http\Controllers\PortfolioController;
use Illuminate\Support\Facades\Route;
use Swoole\Server\Port;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource("currencies", CurrencyController::class)->only(["index","store"]);
Route::resource("portfolio", PortfolioController::class)->except(["show"]);
Route::get("portfolio/{portfolio}/delete", [PortfolioController::class,"delete"])->name("portfolio.delete");
Route::get("portfolio/refresh", [PortfolioController::class, "refresh_rates"])->name("portfolio.refresh");

app/Http/Livewire/CurrencyForm.php
<?php

namespace App\Http\Livewire;

use App\Models\Currency;
use App\Models\Portfolio;
use Livewire\Component;

class CurrencyForm extends Component
{
    public $currency;
    public $search;

    public function mount(Portfolio $portfolio = null, Currency $currency = null)
    {
        $this->search = "";
        $this->currency = null;

        if (isset($portfolio->id)) {
            $currency = $portfolio->currency;
            $this->currency = $currency->id;
        }

        if (isset($currency->id)) {
            $this->currency = $currency->id;
        }
    }

    public function render()
    {
        return view('livewire.currency-form', [
            "currencies" => Currency::search($this->search)->get()
        ]);
    }
}

app/Http/Livewire/CurrencyList.php
<?php

namespace App\Http\Livewire;

use App\Models\Currency;
use Livewire\Component;
use Livewire\WithPagination;

class CurrencyList extends Component
{
    use WithPagination;

    public $per_page;
    public $search;
    public $order_by;
    public $order_asc;

    public function updatingSearch()
    {
        $this->resetPage();
        $this->order_by = "name";
        $this->order_asc = true;
    }

    public function mount()
    {
        $this->per_page = 10;
        $this->search = "";
        $this->order_by = "name";
        $this->order_asc = true;
    }

    public function render()
    {
        return view('livewire.currency-list', [
            "currencies" => Currency::search($this->search)
            ->orderBy($this->order_by, $this->order_asc === true ? "asc" : "desc")
            ->simplePaginate($this->per_page)
        ]);
    }
}

app/Http/Livewire/PortfolioList.php
<?php

namespace App\Http\Livewire;

use App\Models\Portfolio;
use Livewire\Component;
use Livewire\WithPagination;

class PortfolioList extends Component
{
    use WithPagination;

    public $per_page;
    public $search;
    public $order_by;
    public $order_asc;

    public function updatingSearch()
    {
        $this->resetPage();
        $this->order_by = "name";
        $this->order_asc = true;
    }

    public function mount()
    {
        $this->per_page = 10;
        $this->search = "";
        $this->order_by = "name";
        $this->order_asc = true;
    }

    public function render()
    {
        return view('livewire.portfolio-list', [
             "portfolios" => Portfolio::search($this->search)
            ->orderBy($this->order_by, $this->order_asc === true ? "asc" : "desc")
            ->simplePaginate($this->per_page)
        ]);
    }
}

resources/views/livewire/currency-form.blade.php
<section class="flex flex-col gap-4 section">

    <section class="flex flex-col gap-4">
        <h5>Please select a currency from the dropdown below. You can search to narrow the results.</h5>
    </section>

    <section class="">
        <label>Search Currency (name or symbol)</label>
        <input class="input input-primary input-block" wire:model="search" />
    </section>

    <select class="select select-primary select-block" name="currency_id" wire:model="currency">
        <option value="">Please select a currency</option>
        @foreach ($currencies as $currency)
            <option value="{{ $currency->id }}">{{ $currency->name }} ({{ $currency->code }})</option>
        @endforeach
    </select>
    @error('currency_id')
        <section class="p-4 w-full bg-red-500 rounded">{{ $message }}</section>
    @enderror


    <section class="flex flex-row gap-4">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a class="btn btn-error" href="{{ route('portfolio.index') }}">Cancel</a>
    </section>

</section>

resources/views/livewire/currency-list.blade.php
<div class="flex flex-col gap-4">
    <header class="flex flex-row gap-2 w-full">

        <section>
            <label class="">Search (name or code)</label>
            <input wire:model.debounce.300ms="search" class="input input-primary input-block" />
        </section>

        <section>
            <label> Per Page</label>
            <select class="select select-primary select-block" wire:model="per_page">
                <option>10</option>
                <option>25</option>
                <option>50</option>
            </select>
        </section>

        <section class="flex flex-row gap-2">
            <section>
                <label>Order By:</label>
                <select class="select select-primary select-block" wire:model="order_by">
                    <option value="name">Name</option>
                    <option value="code">Code</option>
                </select>
            </section>
            <section>
                <label>Direction</label>
                <select class="select select-primary select-block" wire:model="order_asc">
                    <option value="1">Ascending</option>
                    <option value="0">Descending</option>
                </select>
            </section>
        </section>
    </header>


    <table>
        <thead>
            <tr scope="row">
                <th scope="col">Name</th>
                <th scope="col">Code</th>
                <th scope="col">R1 buys</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($currencies as $currency)
                <tr scope="row">
                    <td data-label="Name">{{ $currency->name }}</td>
                    <td data-label="Code">{{ $currency->code }}</td>
                    <td data-label="Rate">{{ $currency->rate }} {{ \Illuminate\Support\Str::upper($currency->code) }}
                    </td>
                    <td data-label="Actions">
                        <section class="w-full flex flex-row gap-4 justify-evenly">
                            @if ($currency->portfolios->count() > 0)
                                <a class="flex gap-2 justify-evenly btn btn-error"
                                    href="{{ route('portfolio.delete', ['portfolio' => $currency->portfolios->first()]) }}">
                                    <x-lineawesome-times-circle-solid class="w-6 h-6" />
                                    <span>Remove from Portfolio</span>
                                </a>
                            @else
                                <a class="flex gap-2 justify-evenly btn btn-success"
                                    href="{{ route('portfolio.create', ['currency' => $currency->id]) }}">
                                    <x-lineawesome-plus-circle-solid class="w-6 h-6" />
                                    <span>Add To Portfolio</span>
                                </a>
                            @endif
                        </section>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {!! $currencies->links() !!}

</div>

resources/views/livewire/portfolio-list.blade.php
<div class="flex flex-col gap-4">
    <header class="flex flex-row gap-2 w-full">

        <section>
            <label class="">Search (name or code)</label>
            <input wire:model.debounce.300ms="search" class="input input-primary input-block" />
        </section>

        <section>
            <label> Per Page</label>
            <select class="select select-primary select-block" wire:model="per_page">
                <option>10</option>
                <option>25</option>
                <option>50</option>
            </select>
        </section>

        <section class="flex flex-row gap-2">
            <section>
                <label>Order By:</label>
                <select class="select select-primary select-block" wire:model="order_by">
                    <option value="name">Name</option>
                    <option value="code">Code</option>
                </select>
            </section>
            <section>
                <label>Direction</label>
                <select class="select select-primary select-block" wire:model="order_asc">
                    <option value="1">Ascending</option>
                    <option value="0">Descending</option>
                </select>
            </section>
        </section>
    </header>


    <table>
        <thead>
            <tr scope="row">
                <th scope="col">Name</th>
                <th scope="col">Code</th>
                <th scope="col">Rate</th>
                <th scope="col">Latest Rate Date</th>
                <th scope="col">Notes</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($portfolios as $portfolio)
                <tr scope="row">
                    <td data-label="Name">{{ $portfolio->currency->name }}</td>
                    <td data-label="Code">{{ $portfolio->currency->code }}</td>
                    <td data-label="Rate">{{ $portfolio->currency->rate }}</td>
                    <td data-label="Latest Rate Date">{{ $portfolio->currency->rate_date }}</td>
                    <td data-label="Notes">{{ $portfolio->notes }}</td>
                    <td data-label="Actions">
                        <section class="flex gap-4 items-center justify-evenly">
                            <a class="flex gap-2 items-center btn btn-warning"
                                href="{{ route('portfolio.edit', ['portfolio' => $portfolio]) }}">
                                <x-lineawesome-edit-solid class="w-6 h-6" />
                                <span>Edit</span>
                            </a>
                            <a class="flex gap-2 items-center btn btn-error"
                                href="{{ route('portfolio.delete', ['portfolio' => $portfolio]) }}">
                                <x-lineawesome-trash-solid class="w-6 h-6" />
                                <span>Delete</span>
                            </a>
                        </section>
                    </td>
                </tr>
            @empty
                <tr scope="row">
                    <td colspan="5">You do not have any currencies in your portfolio.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {!! $portfolios->links() !!}


</div>